name: CI (Russian)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Russian PDF and upload as an artifact
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: DR_DRNext_User_Manual_mk1_mk2_ru.tex
          texlive_version: latest
          extra_system_packages: coreutils icu inkscape
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: DR_DRNext_User_Manual_mk1_mk2_ru
          path: |
            README.md
            DR_DRNext_User_Manual_mk1_mk2_ru.pdf
  verify:
    name: Verify Russian PDF/A
    runs-on: ubuntu-latest
    needs: build
    container: { image: ghcr.io/jdujava/cuni-thesis-validator }
    steps:
      - name: Get the PDF file from the artifact
        uses: actions/download-artifact@v4
      - name: Verify the PDF file with VeraPDF
        run: verify DR_DRNext_User_Manual_mk1_mk2_ru/*.pdf | tee /dev/stderr | grep -qE 'nonCompliant="0" failedJobs="0"'
